group "Manual Tests"
    include "manual/audio"
    include "manual/cursor"
    include "manual/display"
    include "manual/logger"
    include "manual/message_box"
    include "manual/rectangle_render"
    include "manual/text_render"
group ""

group "Unit Tests"
    include "unit/asset_manager"
    include "unit/colour"
    include "unit/filesystem"
    include "unit/global_resources"
    include "unit/string"
    include "unit/virtual_filesystem"
group ""
