[application]
application_name = "Sandbox"
organisation_name = "test_organisation"

[window]
title = "Stardust Sandbox"
can_resize = false

[filesystem]
assets_archive_relative_path = "assets.pak"
locales_archive_relative_path = "locales.pak"
log_file_relative_path = "log.txt"

    [filesystem.virtual_filepaths]
    default_config_path = "assets/defaults/config.json"
    window_icon_path = "assets/icon/icon.png"
    
[physics]
fixed_timestep = 0.01
velocity_iterations = 8
position_iterations = 3